### ISSUE TITLE
replicate data

### ISSUE THREAD

**Issue by laylaaschuster** [tobjores/Synthetic-Promoter-Designs-Enabled-by-a-Comprehensive-Analysis-of-Plant-Core-Promoters#1]
Hello, I was wondering if you could provide the data from each replicate of the STARR-seq assay or if there was a table available similar to Supplemental Table 1 to see the standard deviation between the replicates for each of the promoters. If this data is already in the repository, could you please point me to where it would be?
Thank you!

**Comment by tobjores** [comment]
Here is a table with the promoter strength in the two biological replicates that I performed:
[promoter-screen_reps.tsv.gz](https://github.com/tobjores/Synthetic-Promoter-Designs-Enabled-by-a-Comprehensive-Analysis-of-Plant-Core-Promoters/files/12457051/promoter-screen_reps.tsv.gz)
